context:
  version: 2.4.0
package:
  name: "bamboo"
  version: '{{ version }}'

source:
  path: .

requirements:
  run:
    - tabulate
    - pandas
    - numpy
    - click
    - astropy
    - robin

build:
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/bin
    - cp bamboo ${PREFIX}/bin/
